/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Feedback_ADC.h"
#include "Switcher.h"
#include "Feedback_aliases.h"
#include "Feedback.h"
#include "Drive_aliases.h"
#include "Drive.h"
#include "PWM_CLK.h"
#include "ADC_CLK.h"
#include "Indicator_aliases.h"
#include "Indicator.h"
#include "ADC_GET_DMA_dma.h"
#include "DMA_ISR.h"
#include "Segments_aliases.h"
#include "Grids_aliases.h"
#include "Tube_Driver.h"
#include "RTC.h"
#include "Button_ISR.h"
#include "Menu_Button_aliases.h"
#include "Menu_Button.h"
#include "DEBOUNCE_CLK.h"
#include "Nav_Button_Reg.h"
#include "HOLDING_CLK.h"
#include "Feedback_ADC_IRQ.h"
#include "Tube_Driver_ClkInternal.h"
#include "Tube_Driver_Seg_Driver_L.h"
#include "Tube_Driver_Com_Driver.h"
#include "Tube_Driver_DMA_Com_dma.h"
#include "Tube_Driver_DMA_Seg_dma.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

